spring:
  application:
    name: enterprise-appointment-api

  datasource:
    url: jdbc:postgresql://localhost:5433/appointments
    username: appointments_user
    password: appointments_pass

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  security:
  jwt:
    secret: "supersecretkeysupersecretkeysupersecretkey"
    access-validity: 900000
    refresh-validity: 604800000

  flyway:
    enabled: true

server:
  port: 8081
